name: Generate sitemap & robots

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Run sitemap generator script
      - name: Run sitemap generator
        run: |
          node scripts/generate-sitemap.js

      # Run robots.txt generator script
      - name: Run robots generator
        run: |
          node scripts/generate-robots.js

      # Show sitemap preview in logs
      - name: Show sitemap preview
        run: |
          echo "---- sitemap.xml preview ----"
          head -n 50 sitemap.xml || true

      # Commit updated sitemap + robots.txt
      - name: Commit sitemap & robots if changed
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add sitemap.xml robots.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update sitemap.xml & robots.txt [ci skip]"
          git push

      # Ping Google
      - name: Ping Google
        run: |
          curl "http://www.google.com/ping?sitemap=https://discipline-se-success-tak.vercel.app/sitemap.xml"

      # Ping Bing
      - name: Ping Bing
        run: |
          curl "http://www.bing.com/ping?sitemap=https://discipline-se-success-tak.vercel.app/sitemap.xml"
