name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run sitemap generator
        run: |
          mkdir -p scripts
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' > sitemap.xml
          echo '  <url><loc>https://discipline-se-success-tak.vercel.app/</loc><priority>1.0</priority></url>' >> sitemap.xml
          echo '  <url><loc>https://discipline-se-success-tak.vercel.app/blog.html</loc><priority>0.9</priority></url>' >> sitemap.xml
          echo '  <url><loc>https://discipline-se-success-tak.vercel.app/#sample</loc><priority>0.8</priority></url>' >> sitemap.xml
          echo '  <url><loc>https://discipline-se-success-tak.vercel.app/#feedback</loc><priority>0.8</priority></url>' >> sitemap.xml
          echo '  <url><loc>https://discipline-se-success-tak.vercel.app/#about</loc><priority>0.7</priority></url>' >> sitemap.xml
          echo '</urlset>' >> sitemap.xml

      - name: Show produced sitemap
        run: |
          echo "---- sitemap.xml preview ----"
          head -n 40 sitemap.xml || true

      - name: Commit sitemap if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: regenerate sitemap.xml"
          git push
