name: Generate sitemap & robots and ping search engines

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run sitemap generator
        run: node scripts/generate-sitemap.js

      - name: Run robots.txt generator
        run: node scripts/generate-robots.js

      - name: Show produced files
        run: |
          echo "---- sitemap.xml ----"
          head -n 40 sitemap.xml || true
          echo "---- robots.txt ----"
          cat robots.txt || true

      - name: Commit sitemap & robots.txt if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml robots.txt
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: regenerate sitemap.xml & robots.txt"
          git push

      - name: Ping Google
        run: |
          echo "Pinging Google..."
          curl -s "https://www.google.com/ping?sitemap=https://discipline-se-success-tak.vercel.app/sitemap.xml" -w "\nhttp_status:%{http_code}\n"

      - name: Ping Bing
        run: |
          echo "Pinging Bing..."
          curl -s "https://www.bing.com/webmaster/ping.aspx?siteMap=https://discipline-se-success-tak.vercel.app/sitemap.xml" -w "\nhttp_status:%{http_code}\n"
